services:
  mysql:
    image: mysql:8.0
    container_name: side_mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: side_adminer
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: